name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  NPM_CONFIG_AUDIT: false
  NPM_CONFIG_FUND: false
  NPM_CONFIG_UPDATE_NOTIFIER: false

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install root dependencies
      run: npm ci --silent

    - name: Install backend dependencies
      working-directory: ./backend
      run: npm ci --silent

    - name: Install frontend dependencies
      working-directory: ./frontend
      run: npm ci --silent

    - name: Run backend linting
      working-directory: ./backend
      run: npm run lint

    - name: Run frontend linting
      working-directory: ./frontend
      run: npm run lint

    - name: Run backend tests
      working-directory: ./backend
      run: npm test

    - name: Run frontend tests
      working-directory: ./frontend
      run: npm test -- --coverage --watchAll=false

    - name: Build frontend
      working-directory: ./frontend
      run: npm run build